CREATE TABLE `alarm_collection_v2` (
   `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增主键ID',
   `road_id` varchar(255) NOT NULL COMMENT '告警集对应道路编码',
   `device_id` varchar(255) NOT NULL COMMENT '告警集点位设备ID',
   `device_name` varchar(255) DEFAULT NULL COMMENT '告警集点位名称',
   `milestone` int(11) DEFAULT NULL COMMENT '桩米号',
   `event_type` varchar(255) DEFAULT NULL COMMENT '告警集事件类型',
   `disposal_advice` int(11) DEFAULT NULL COMMENT '处置建议：0-无法判断、1-疑似误报、2-尽快确认、3-无需处理、4-重复报警',
   `related_tbl_id_list` text COMMENT '关联告警tblId列表',
   `related_alarm_id_list` text COMMENT '关联告警alarmId列表',
   `earliest_alarm_time` datetime DEFAULT NULL COMMENT '关联最新告警事件时间',
   `latest_alarm_time` datetime DEFAULT NULL COMMENT '关联最新告警事件时间',
   `related_alarm_num` int(10) NOT NULL COMMENT '关联告警数量',
   `collection_status` int(11) DEFAULT NULL COMMENT '告警集状态：1-使用中，2-已关闭',
   `related_source_type` int(11) DEFAULT NULL COMMENT '告警集来源类型：0-未知，1-非摩托车，2-摩托车',
   `person_check_flag` int(11) DEFAULT '0' COMMENT '人工检验标签_是否关联正确：0-未核查，1-是，2-否',
   `person_check_reason` varchar(256) DEFAULT NULL COMMENT '人工检验判断原因',
   `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '告警集创建时间',
   `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '告警集更新时间',
   PRIMARY KEY (`id`),
   KEY `idx_event_type` (`event_type`),
   KEY `idx_road_id` (`road_id`),
   KEY `idx_create_time` (`create_time`),
   KEY `idx_latest_alarm_time` (`latest_alarm_time`),
   KEY `idx_person_flag_time` (`person_check_flag`,`latest_alarm_time`)
) ENGINE=InnoDB AUTO_INCREMENT=51117 DEFAULT CHARSET=utf8mb4 COMMENT='核检告警集'