CREATE TABLE IF NOT EXISTS `alarm_frame_image_info` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID，自增',
  `alarm_id` VARCHAR(255) NOT NULL COMMENT '关联告警事件ID（外键）',
  `frame_num` INT DEFAULT NULL COMMENT '抽帧帧数',
  `image_sort_no` INT NOT NULL COMMENT '图片排序编号',
  `image_url` VARCHAR(1024) NOT NULL COMMENT '图片URL',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警抽帧图片信息表';