CREATE TABLE `collection_group_record` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `collection_id` varchar(255) NOT NULL COMMENT '归属告警集id',
    `group_id` varchar(255) NOT NULL COMMENT '分组ID',
    `group_image_url` varchar(255) NOT NULL COMMENT '分组图片',
    `group_event_type` varchar(255) NOT NULL COMMENT '分组事件类型',
    `alarm_id` varchar(255) NOT NULL COMMENT '告警ID',
    `image_path` varchar(255) NOT NULL COMMENT '图片路径',
    `video_path` varchar(255) NOT NULL COMMENT '视频路径',
    `event_type` varchar(255) NOT NULL COMMENT '事件类型',
    `alarm_time` datetime NOT NULL COMMENT '告警时间',
    `extract_image_url` varchar(255) DEFAULT NULL COMMENT '抠图图片链接',
    `alarm_element` varchar(255) DEFAULT NULL COMMENT '告警物体类型',
    `point1_x` int DEFAULT NULL COMMENT '提框坐标点位1x',
    `point1_y` int DEFAULT NULL COMMENT '提框坐标点位1y',
    `point2_x` int DEFAULT NULL COMMENT '提框坐标点位2x',
    `point2_y` int DEFAULT NULL COMMENT '提框坐标点位2y',
    `lead_compare_iou` int DEFAULT NULL COMMENT '与上条记录对比iou结果',
    `lead_compare_minute` int DEFAULT NULL COMMENT '与上条记录对比时长差距',
    `group_type` int DEFAULT NULL COMMENT '告警组类型：0-无法判断告警组、1-正检告警组、2-误检告警组',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `modify_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录修改时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='告警集分组记录表';