CREATE TABLE IF NOT EXISTS `kafka_original_alarm_record` (
   `id` VARCHAR(64) PRIMARY KEY COMMENT '主键ID',
   `event_id` VARCHAR(64) COMMENT '事件ID',
   `name_inp` VARCHAR(255) COMMENT '高速名称',
   `direction` VARCHAR(10) COMMENT '方向角度',
   `direction_type` VARCHAR(64) DEFAULT NULL COMMENT '方向类型',
   `alarm_time` DATETIME COMMENT '报警时间',
   `milestone` INT COMMENT '起始里程',
   `end_milestone` INT COMMENT '终止里程',
   `road_id` VARCHAR(64) COMMENT '道路ID',
   `organization_id` VARCHAR(64) COMMENT '所属组织ID',
   `alert_level` VARCHAR(10) COMMENT '预警等级',
   `latitude` DOUBLE COMMENT '纬度',
   `longitude` DOUBLE COMMENT '经度',
   `event_type` VARCHAR(50) COMMENT '事件类型',
   `event_type_id` VARCHAR(64) COMMENT '事件类型ID',
   `content` TEXT COMMENT '事件描述',
   `content_custom` TEXT DEFAULT NULL COMMENT '自定义内容',
   `image_path` VARCHAR(1024) COMMENT '图片路径',
   `video_path` VARCHAR(1024) COMMENT '视频路径',
   `source` VARCHAR(50) COMMENT '事件来源',
   `source_id` VARCHAR(64) COMMENT '来源ID',
   `company` VARCHAR(50) COMMENT '公司名称',
   `company_id` VARCHAR(64) COMMENT '公司ID',
   `direction_des` VARCHAR(50) COMMENT '方向描述',
   `source_event_id` VARCHAR(128) COMMENT '来源事件ID',
   `jam_speed` VARCHAR(32) DEFAULT NULL COMMENT '拥堵速度',
   `long_time` VARCHAR(32) DEFAULT NULL COMMENT '拥堵时长',
   `jam_dist` VARCHAR(32) DEFAULT NULL COMMENT '拥堵距离',
   `weather` VARCHAR(64) DEFAULT NULL COMMENT '天气信息',
   `deal_flag` VARCHAR(10) COMMENT '处置标志',
   `deal_time` DATETIME DEFAULT NULL COMMENT '处置时间',
   `read_flag` VARCHAR(10) COMMENT '阅读标志',
   `read_time` DATETIME DEFAULT NULL COMMENT '阅读时间',
   `voice_url` VARCHAR(512) DEFAULT NULL COMMENT '语音路径',
   `user_id` VARCHAR(64) COMMENT '用户ID',
   `suspend_time` DATETIME DEFAULT NULL COMMENT '挂起时间',
   `server_ip` VARCHAR(64) DEFAULT NULL COMMENT '服务端IP',
   `client_ip` VARCHAR(64) DEFAULT NULL COMMENT '客户端IP',
   `popup_flag` VARCHAR(10) DEFAULT NULL COMMENT '弹窗标志',
   `voice_flag` VARCHAR(10) DEFAULT NULL COMMENT '语音标志',
   `phone` VARCHAR(32) DEFAULT NULL COMMENT '手机号',
   `frame_flag` VARCHAR(10) DEFAULT NULL COMMENT '框选标志',
   `destroy_time` DATETIME DEFAULT NULL COMMENT '销毁时间',
   `alarm_place` VARCHAR(255) DEFAULT NULL COMMENT '报警地点',
   `lane_index` INT DEFAULT NULL COMMENT '车道编号',
   `device_id` VARCHAR(64) COMMENT '设备ID',
   `countermeasures` TEXT DEFAULT NULL COMMENT '对策建议',
   `supplement` TEXT DEFAULT NULL COMMENT '补充信息',
   `rel_alarm_id` VARCHAR(64) DEFAULT NULL COMMENT '关联报警ID',
   `uuid` VARCHAR(64) DEFAULT NULL COMMENT 'UUID',
   `situational_list` TEXT DEFAULT NULL COMMENT '态势信息列表',
   `redundance` TEXT DEFAULT NULL COMMENT '冗余字段',
   `ramp_id` VARCHAR(64) DEFAULT NULL COMMENT '匝道ID',
   `toll_id` VARCHAR(64) DEFAULT NULL COMMENT '收费站ID',
   `create_time` DATETIME COMMENT '创建时间',
   `create_time_sys` DATETIME COMMENT '系统创建时间',
   `modify_time_sys` DATETIME COMMENT '系统修改时间',
   `consume_tag int` comment '程序消费处理标签:0未处理完成，1处理完成',
   `db_create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '数据库插入时间',
   `db_update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据库更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件信息表';

