spring:
  datasource:
    dynamic:
      primary: primary   # 默认数据源
      strict: false      # 未匹配到时是否报错，false 表示走默认数据源
      datasource:
        primary:
          url: jdbc:mysql://127.0.0.1:3306/event_manage?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
          username: jwgateway
          password: 123123
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-pool-size: 10
            min-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000

        secondary:
          url: jdbc:mysql://127.0.0.1:3306/cloud_business?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
          username: jwgateway
          password: 123123
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            max-pool-size: 10
            min-idle: 5
            idle-timeout: 30000
            max-lifetime: 1800000