spring:
  datasource:
#    url: jdbc:mysql://47.92.219.27:3306/event_manage?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: Yuce@2020pwd
    url: jdbc:mysql://127.0.0.1:3306/event_manage?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: jwgateway
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000